### ISSUE TITLE
Test failure with key4hep nightlies

### ISSUE THREAD

**Issue by vvolkl** [key4hep/k4SimDelphes#42]
See discussion in #23

**Comment by tmadlener** [comment]
This is most probably related to the following bit of output of the standalone run of the delphes converter (in the nightlies setup):

```
 --------  End PYTHIA Event Listing  -----------------------------------------------------------------------------------------------
**** WARNING: No matching ReconstructedParticle was found for a Delphes muon
** 99 events processed
```

Since this leads to cases where there are almost definitely differences between the delphes output and the edm4hep output, I have initially "carefully chosen a random seed" where no such cases occur in the 1000 events that we use for these tests. However, it seems that due to slightly different versions even with this special seed we get some of those events. This is in any case a rather unsatisfying solution to the whole problem, so it should be addressed.

Why the comparison executable just crashes in such a case is another question, and I will investigate if the crash is related to the issue above or whether it is something different.
