### ISSUE TITLE
[framework] Segfault when Edm4hepConverter created in initialize

### ISSUE THREAD

**Issue by vvolkl** [key4hep/k4SimDelphes#43]
See discussion in #23

**Comment by andresailer** [comment]
direct link to the discussion? https://github.com/key4hep/k4SimDelphes/pull/23#discussion_r608442630

**Comment by tmadlener** [comment]
The reason for the segmentation fault is that internally the converter holds a `std::unordered_map<std::string, podio::CollectionBase*>`. The converter assumes that something external takes owenership of these **exactly once**. This works in the standalone case, where the `EventStore` takes this role. In the framework case the `DataHandle` of the first event takes ownership, hence, on the second event the pointers are no longer accessible.

The underlying reason is fixed by #85. I will open a separate pull request making the actual changes to not instantiate the converter each event once that has been merged.
