### ISSUE TITLE
Breaking changes in upstream delphes to the HepMCReader

### ISSUE THREAD

**Issue by vvolkl** [key4hep/k4SimDelphes#51]
See nightlies build failure https://gitlab.cern.ch/key4hep/k4-deploy/-/jobs/14065802

DelphesHepMCReader.h is gone and replaced by DelphesHepMCReader2.h (a DelphesHepMCReader3.h was introduced as well).

Instead of propagating the changes, it might actually be better to use the framework for this reader instead.

**Comment by tmadlener** [comment]
Alternatively we could decide on one of the two HepMC versions we want to support and only support that one, so that we still have at least one standalone version to read HepMC files.

We had a somewhat similar discussion already some time ago in key4hep/EDM4hep#60, but we never switched to HepMC3 there. Looking at the key4hep-stack it seems that we have both versions in any case. We could decide on one version and use that as a dependency in all packages that we maintain.

**Comment by vvolkl** [comment]
I think once we adapt to the breaking change, it shouldn't be too much of a problem to add hepmc3 support as well. My point was about the breaking change: If we use the framework, we avoid using some header files like DelphesHepMCReader.h that the delphes developers may regard as semi-private and may change again in the future. Also, going further we'll have to duplicate some things like metadata handling and make sure this is kept in sync with the framework.

On the other hand, the standalone parts do not have all the gaudi dependencies, which can be an advantage for people trying to build parts of the software themselves.
